export const GET_ADVERTISING_LIST_REQUEST = "GET_ADVERTISING_LIST_REQUEST";
export const GET_ADVERTISING_LIST_SUCCESS = "GET_ADVERTISING_LIST_SUCCESS";
export const GET_ADVERTISING_LIST_FAIL = "GET_ADVERTISING_LIST_FAIL";
